using nmsCommon;
using nmsConnectionClass;
using nmsLanguage;
using RemovingWhiteSpacesAspNet;
using System;
using System.Configuration;
using System.IO;
using System.Web;
using System.Web.Profile;
using System.Web.SessionState;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;
using Telerik.Web.UI;

namespace ePrint.olddata
{
    public partial class Default : BaseClass, IRequiresSessionState
    {
        private Global gloobj = new Global();

        private commonClass objJava = new commonClass();

        public static string WhereCondition;

        public static string sortdirection;

        public static string SortedBy;

        public string ServerName = "noserverfound";

        private string oldDataPath = string.Empty;

        protected int CompanyID;

        public languageClass objLangClass = new languageClass();

        protected Global ApplicationInstance
        {
            get
            {
                return (Global)this.Context.ApplicationInstance;
            }
        }

        protected DefaultProfile Profile
        {
            get
            {
                return (DefaultProfile)this.Context.Profile;
            }
        }

        static Default()
        {
            Default.WhereCondition = string.Empty;
            Default.sortdirection = string.Empty;
            Default.SortedBy = string.Empty;
        }

        public Default()
        {
        }

        protected void clrFilters_Click(object sender, EventArgs e)
        {
            GridColumn[] autoGeneratedColumns = this.RadGrid1.MasterTableView.AutoGeneratedColumns;
            for (int i = 0; i < (int)autoGeneratedColumns.Length; i++)
            {
                GridColumn empty = autoGeneratedColumns[i];
                empty.CurrentFilterFunction = GridKnownFunction.NoFilter;
                empty.CurrentFilterValue = string.Empty;
            }
            this.RadGrid1.MasterTableView.FilterExpression = string.Empty;
            this.RadGrid1.MasterTableView.Rebind();
        }

        protected void ddlFiles_SelectedIndexChanged(object sender, EventArgs e)
        {
            this.ObjectDataSource1.SelectParameters.Clear();
            this.ObjectDataSource1.SelectMethod = "GetDate";
            this.ObjectDataSource1.SelectParameters.Add("FilePath", string.Concat(this.oldDataPath, this.ddlFiles.SelectedItem.Text));
            this.ObjectDataSource1.TypeName = "OLDDATA";
        }

        protected void Page_Load(object sender, EventArgs e)
        {
            if (ConnectionClass.ServerName != null)
            {
                this.ServerName = ConnectionClass.ServerName;
            }
            string[] item = new string[] { EprintConfigurationManager.AppSettings["securedocpath"], this.ServerName, "//", this.Session["companyid"].ToString(), "/olddata/" };
            this.oldDataPath = string.Concat(item);
            global.pageName = "setting";
            global.pgName = "";
            this.gloobj.setpagename("setting");
            base.Navigation_Path("<a href=../welcome.aspx class='subnavigator'  style='text-decoration:underline;'>Home</a>&nbsp;>&nbsp;<a href=../settings/settings.aspx class='subnavigator'  style='text-decoration:underline;'>Settings</a>", "&nbsp;>&nbsp;Old Data");
            base.Title = this.objLanguage.convert(global.pageTitle("Old Data", int.Parse(this.Session["companyid"].ToString()), this.Session["companyName"].ToString()));
            if (!base.IsPostBack)
            {
                this.ObjectDataSource1.SelectParameters.Clear();
                this.ObjectDataSource1.SelectMethod = "GetDate";
                this.ObjectDataSource1.SelectParameters.Add("FilePath", string.Concat(this.oldDataPath, "XMLFile.xml"));
                this.ObjectDataSource1.TypeName = "OLDDATA";
            }
            Default olddataDefault = this;
            olddataDefault.oldDataPath = string.Concat(olddataDefault.oldDataPath, this.Session["companyID"], "/");
            if (!base.IsPostBack)
            {
                this.Session["OLDDATA"] = null;
                DirectoryInfo directoryInfo = new DirectoryInfo(this.oldDataPath);
                this.ddlFiles.DataSource = directoryInfo.GetFiles();
                this.ddlFiles.DataBind();
                this.ddlFiles.Items.Insert(0, "");
                this.ddlFiles.Items[0].Text = "Please select";
            }
            if (this.ddlFiles.Items.Count <= 2)
            {
                this.spn_Selectfile.Visible = false;
                this.ddlFiles.Visible = false;
                this.ObjectDataSource1.SelectParameters.Clear();
                this.ObjectDataSource1.SelectMethod = "GetDate";
                this.ObjectDataSource1.SelectParameters.Add("FilePath", string.Concat(this.oldDataPath, this.ddlFiles.Items[1].Text));
                this.ObjectDataSource1.TypeName = "OLDDATA";
            }
        }

        protected void radGrid1_ColumnCreated(object sender, GridColumnCreatedEventArgs e)
        {
            e.Column.AutoPostBackOnFilter = true;
        }

        protected void radGrid1_ItemDataBound(object sender, GridItemEventArgs e)
        {
            if (e.Item.ItemType == GridItemType.Item || e.Item.ItemType == GridItemType.AlternatingItem)
            {
                GridDataItem item = (GridDataItem)e.Item;
                try
                {
                    TableCell shortDateString = item["Delivery Date"];
                    DateTime dateTime = Convert.ToDateTime(item["Delivery Date"].Text);
                    shortDateString.Text = dateTime.ToShortDateString();
                    item["Delivery Date"].Text = this.objJava.Eprint_return_Date_Before_View(item["Delivery Date"].Text, Convert.ToInt32(this.Session["companyID"]), Convert.ToInt32(this.Session["UserID"]), true);
                }
                catch
                {
                }
                try
                {
                    TableCell tableCell = item["Estimate Date"];
                    DateTime dateTime1 = Convert.ToDateTime(item["Estimate Date"].Text);
                    tableCell.Text = dateTime1.ToShortDateString();
                    item["Estimate Date"].Text = this.objJava.Eprint_return_Date_Before_View(item["Estimate Date"].Text, Convert.ToInt32(this.Session["companyID"]), Convert.ToInt32(this.Session["UserID"]), true);
                }
                catch
                {
                }
                try
                {
                    TableCell item1 = item["Invoice Date"];
                    DateTime dateTime2 = Convert.ToDateTime(item["Invoice Date"].Text);
                    item1.Text = dateTime2.ToShortDateString();
                    item["Invoice Date"].Text = this.objJava.Eprint_return_Date_Before_View(item["Invoice Date"].Text, Convert.ToInt32(this.Session["companyID"]), Convert.ToInt32(this.Session["UserID"]), true);
                }
                catch
                {
                }
                try
                {
                    TableCell shortDateString1 = item["Job Completed"];
                    DateTime dateTime3 = Convert.ToDateTime(item["Job Completed"].Text);
                    shortDateString1.Text = dateTime3.ToShortDateString();
                    item["Job Completed"].Text = this.objJava.Eprint_return_Date_Before_View(item["Job Completed"].Text, Convert.ToInt32(this.Session["companyID"]), Convert.ToInt32(this.Session["UserID"]), true);
                }
                catch
                {
                }
                try
                {
                    TableCell tableCell1 = item["PO Required Date"];
                    DateTime dateTime4 = Convert.ToDateTime(item["PO Required Date"].Text);
                    tableCell1.Text = dateTime4.ToShortDateString();
                    item["PO Required Date"].Text = this.objJava.Eprint_return_Date_Before_View(item["PO Required Date"].Text, Convert.ToInt32(this.Session["companyID"]), Convert.ToInt32(this.Session["UserID"]), true);
                }
                catch
                {
                }
            }
            GridColumn[] autoGeneratedColumns = this.RadGrid1.MasterTableView.AutoGeneratedColumns;
            for (int i = 0; i < (int)autoGeneratedColumns.Length; i++)
            {
                autoGeneratedColumns[i].CurrentFilterFunction = GridKnownFunction.Contains;
            }
        }
    }
}