INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('TICKET','Open Activities',0,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Campaign','Open Activities',0,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Campaign','Marketing',0,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Contract','Notes',0,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Asset','Notes',0,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Asset','Open Activities',1,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Contract','Open Activities',1,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Product','Standard Price',1,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Price','Product',1,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Campaign','Active History',1,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('TICKET','Active History',1,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Lead','Notes',1,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('CLIENT','Notes',1,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Contact','Notes',1,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('opportunity','Notes',1,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('opportunity','Open Activities',2,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Contact','Open Activities',2,'#DDDDDD',@companyId,0);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('CLIENT','Open Activities',2,'#DDDDDD',@companyId,0);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('TICKET','Notes',2,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Campaign','Notes',2,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Solution','Notes',2,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Product','Price Books',2,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Contract','Active History',2,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Asset','Active History',2,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Asset','Ticket',3,'#DDDDDD',@companyId,0);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Home','Task',3,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Solution','Attachments',3,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Contact','HTML Email',3,'#DDDDDD',@companyId,0);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('TICKET','Attachment',3,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('CLIENT','Active History',3,'#DDDDDD',@companyId,0);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Contact','Active History',3,'#DDDDDD',@companyId,0);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('opportunity','Active History',3,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('opportunity','Contact Role',4,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Contact','Opportunity',4,'#DDDDDD',@companyId,0);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('CLIENT','Contacts',4,'#DDDDDD',@companyId,0);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Lead','Active History',4,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('TICKET','Ticket History',4,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Campaign','Opportunity',4,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Solution','Ticket',4,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Solution','Solution History',4,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Home','Opportunity',4,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Campaign','Attachment',4,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Asset','Attachment',4,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Contract','Approval Request',4,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Contract','Contract History',5,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Home','Lead',5,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('TICKET','Solution',5,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('CLIENT','Attachment',5,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Contact','Attachment',5,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('opportunity','Attachment',5,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('CLIENT','Opportunity',5,'#DDDDDD',@companyId,0);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Contact','Ticket',5,'#DDDDDD',@companyId,0);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('opportunity','Competitors',5,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('opportunity','Stage History',6,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('CLIENT','Ticket',6,'#DDDDDD',@companyId,0);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Contract','Attachment',6,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('CLIENT','Partners',7,'#DDDDDD',@companyId,0);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Lead','Attachment',7,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Home','Graph',8,'',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('CLIENT','HTML Email',8,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Lead','Open Activities',10,'#DDDDDD',@companyId,1);
INSERT INTO tb_customizesubsection (sectionname,subsectionname,ordernumber,navigationcolor,companyid,isdisplay) VALUES ('Lead','HTML Email',13,'#DDDDDD',@companyId,1);
