using nmsnotesclass;
using Printcenter.DataAccessLayer.DbNotes;
using System;
using System.Data;

namespace Printcenter.BusinessAccessLayer.Notes
{
	public class Notes
	{
		public Notes()
		{
		}

		public static void insert_Activity_History(int CompanyID, string NoteType, string ModuleName, long ModuleID, string Description, DateTime CreateDate, int CreateUserId, long ItemID)
		{
		}

		public void NotesAdd(notesclass obj)
		{
		}


		public static DataTable select_EstimateType_for_Activity_History(long EstimateID, long EstimateItemID)
		{
			return (new DbNotes()).select_EstimateType_for_Activity_History(EstimateID, EstimateItemID);
		}

		public static DataTable select_item_number_for_Activity_History(long EstimateID, long EstimateItemID, string ModuleType)
		{
			return (new DbNotes()).select_item_number_for_Activity_History(EstimateID, EstimateItemID, ModuleType);
		}

		public static DataTable select_item_Title_for_Activity_History(int CompanyID, long EstimateID, long EstimateItemID, string EstimateType)
		{
			return (new DbNotes()).select_item_Title_for_Activity_History(CompanyID, EstimateID, EstimateItemID, EstimateType);
		}

		public enum NotesType
		{
			EstCreate,
			EstInfoRerun,
			EstItemRerun,
			EstAdd_attachment,
			EstNewItemAdd,
			EstChangeStatus,
			EstItemTitleEdit,
			EstItemDescPhrase,
			EstItemDesc,
			EstCopied,
			EstNewCopied,
			EstSubTotalForOthers,
			EstSubTotal,
			EstProMargin,
			EstProMarginPrice,
			EstTax,
			EstTemplateView,
			EstTempViewEdit,
			EstTempViewEditSent,
			EstTemplateSent,
            EstTemplateSentWithStatusChange,
            EstProgWithPOandDel,
			EstProgWithPO,
			EstProgWithDel,
			EstProgWithOutPOandDel,
			EstItemDeleted,
			EstSubItemDelte,
			EstSubItemAdded,
			EstSubItemRerun,
			EstItemProgtoJob,
			EstArchivedandProgtoJob,
			EstitemProcreated,
			EstitemProUpdated,
			EstItemArchived,
			EstUnArchived,
			EstItemUnArchived,
			SupplierRFQTempSend,
			OrdChangeStatus,
			OrdItemRerun,
			OrderAdd_attachment,
			OrdTempViewEdit,
			OrdProgWithPOandDel,
			OrdProgWithPO,
			OrdProgWithDel,
			OrdProgWithOutPOandDel,
			OrderTempSend,
            OrderTempSendWithStatusChange,
            OrderTemplateView,
			OrdItemDeleted,
			OrderItemTitleEdit,
			OrderTax,
			OrderSubTotalForOthers,
			OrderSubTotal,
			OrderProMargin,
			OrderProMarginPrice,
			OrderSubItemDelte,
			OrderSubItemRerun,
			OrderItemDeleted,
			OrderItemProgtoJob,
			OrdArchivedandProgtoJob,
			OrditemProcreated,
			OrdItemArchived,
			OrdUnArchived,
			OrdItemUnArchived,
			JobCreate,
			JobDirCreate,
			JobInfoRerun,
			JobItemRerun,
			JobRevertWithPOandDel,
			JobRevertWithPO,
			JobRevertWithDel,
			JobRevertWithOutPOandDel,
			JobAdd_attachment,
			JobNewItemAdd,
			JobChangeStatus,
			JobItemTitleEdit,
			JobItemDeleted,
			JobTemplateView,
			JobTempViewEdit,
			JobTempViewEditSent,
			JobTemplateSent,
            JobTemplateSentWithStatusChange,
            JobPOCreate,
			JobPOViewd,
			JobPOEdited,
			JobPODelete,
			JobPOViedInTemp,
			JobPOViedInTempEdit,
			JobPOViedInTempEditSend,
			JobPOViedInTempSend,
			JobDelCreate,
			JObDelVied,
			JobDelEdit,
			JobDelDelete,
			JobDelViewTemp,
			JobDelEditTemp,
			JobDelEditTempSend,
			JobDelTempSend,
			JobProgInvPayment,
			JobProgInv,
			JobProgInvDetail,
			JobCardEdit,
			JobCardEditSend,
			JobItemDescPhrase,
			JobCopied,
			JobNewCopied,
			JobSubTotal,
			JobSubTotalForOthers,
			JobProMargin,
			JobProMarginPrice,
			JobTax,
			OrdJobProgInv,
			JobSubItemRerun,
			JobSubItemDelte,
			JobItemProgInv,
			JobRevertWithOutPOandDelFromorder,
			JobRevertWithPOandDelFromorder,
			JobRevertWithPOFromorder,
			JobRevertWithDelFromorder,
			JobArchivedandProgtoInv,
			JobitemProcreated,
			JobitemProUpdated,
			JobItemRevertedFromEstimate,
			JobItemRevertedFromOrder,
			JobItemArchived,
			JobUnArchived,
			JobItemUnArchived,
			InvDirCreate,
			InvCreate,
			MultipleInvCreate,
			InvInfoRerun,
			InvItemRerun,
			InvAdd_attachment,
			InvNewItemAdd,
			InvChangeStatus,
			InvItemTitleEdit,
			InvItemDeleted,
			InvTemplateView,
			InvTempViewEdit,
			InvTempViewEditSent,
			InvTemplateSent,
            InvTemplateSentWithStatusChange,
            InvItemDescPhrase,
			InvCopied,
			InvNewCopied,
			InvSubTotal,
			InvSubTotalForOthers,
			InvProMargin,
			InvProMarginPrice,
			InvTax,
			InvPayment,
			InvNotPayment,
			InvfullPayment,
			InvfullPaid,
			InvPartPaid,
			InvPaymentDelete,
			InvPaymentUpdate,
			InvfullPaidMain,
			InvSubItemRerun,
			InvoiceSubItemDelte,
			InvCreatedWithPayment,
			InvCreatedWithoutPayment,
			InvitemProcreated,
			InvitemProUpdated,
			InvArchived,
			InvItemArchived,
			InvUnArchived,
			InvItemUnArchived,
			POCreated,
			POUpdate,
			POChangeStatus,
			POViewTemp,
			POTempEdit,
			POAdd_attachment,
			POTempEditSend,
			POTempSend,
            POTempSendWithStatusChange,
            POCreatedFromJob,
			POCopied,
			PONewCopied,
			POItemInserted,
			DelCreated,
			DelUpdate,
			DeliveryDelUpdate,
			DeliveryGoodsDelivered,
			DelChangeStatus,
			DelViewTemp,
			DelTempEdit,
			DelAdd_attachment,
			DelTempEditSend,
			DelTempSend,
            DelTempSendWithStatusChange,
            DelCreatedFromJob,
			DelCarInfoChanged,
			CopyItem,
			EstDetailUpdate,
			JobDetailUpdate,
			InvDetailUpdate,
			ArtworkAttchmentAdded,
			ArtworkAttchmentUpdated,
            InvExported,
            InvUnexported,
			ManualProofApproval,
			ManualProofRejection
        }
	}
}
